#!/usr/bin/env python3
#
# Copyright (c) 2017-18 Jonathan Weyn <jweyn@uw.edu>
#
# See the file LICENSE for your rights.

"""
Launching script for the theta-e forecast verification system.
"""

import sys
from argparse import ArgumentParser

# Import the main engine
import thetae
import thetae.engine


# ==================================================================================================================== #
# Parse the input arguments
# ==================================================================================================================== #

def parse_args():
    """
    Parse input arguments.
    """

    parser = ArgumentParser()
    parser.add_argument("config", help="Path to theta-e config file")
    parser.add_argument("-n", "--no-output", action="store_true", dest="no_output",
                        help="Suppress all plot and web output")
    parser.add_argument("-v", "--version", action="store_true", dest="version",
                        help="Display version number then exit")
    parser.add_argument("--backfill-historical", action="store", dest="b_stid", nargs='*',
                        help="Backfill the historical data for any number of stations; if no stations are specified, "
                             "backfill all stations in the config file.")
    parser.add_argument("--remove", action="store", dest="r_stid", nargs='*',
                        help="Remove the database tables for any number of stations; if no stations are specified, "
                             "nothing is done.")
    arguments = parser.parse_args()

    if arguments.version:
        print('thetae module version: %s' % thetae.__version__)
        sys.exit(0)

    return arguments


args = parse_args()


# ==================================================================================================================== #
# Launch the main engine
# ==================================================================================================================== #

thetae.engine.main(args)
